### ISSUE TITLE
I cannot get this to work :c 

### ISSUE THREAD

**Issue by k1llerk3ks** [iwalton3/python-spotled#3]
Whenever i try to run the test script from readme i get: (i changed the MAC of the device a little)
```
Traceback (most recent call last):
  File "/home/myuser/python-spotled/example/test.py", line 2, in <module>
    sender = spotled.LedConnection('3b10b03d6ba4')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/spotled/__init__.py", line 770, in __init__
    self._ensure_connection()
  File "/usr/lib/python3.11/site-packages/spotled/__init__.py", line 812, in _ensure_connection
    raise TimeoutError("Timeout exceeded waiting for bluetooth connection.")
TimeoutError: Timeout exceeded waiting for bluetooth connection.
```

**Comment by gilraeon** [comment]
The MAC address you are using is the one you got from a gattool scan, right?

Also I think the correct format for MAC address is colon separated, e.g. 

spotled.LedConnection('25:BC:4E:5D:52:B0')

**Comment by k1llerk3ks** [comment]
Sorry, i typed a bit fast - i tested the format `spotled.LedConnection('25:BC:4E:5D:52:B0')` too, also with lowercase chars.

I am running Manjaro btw.
