### ISSUE TITLE
issues installing 'gattlib'?

### ISSUE THREAD

**Issue by mcbazza** [iwalton3/python-spotled#8]
If you get

> (env) :~/Documents/python-spotled $ pip3 install gattlib                                       Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple                               Collecting gattlib                                                                                           Using cached gattlib-0.20210616.tar.gz (54 kB)                                                             Preparing metadata (setup.py) ... error                                                                    error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.                                                       │ exit code: 1
>   ╰─> [15 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>                                                                       File "<pip-setuptools-caller>", line 34, in <module>                                                       File "/tmp/pip-install-c9v2na2p/gattlib_476160e2cf6b4c388253a2bd5d511442/setup.py", line 62, in <module>                                                                                                                boost_py = get_boost_version()
>                      ^^^^^^^^^^^^^^^^^^^                                                                           File "/tmp/pip-install-c9v2na2p/gattlib_476160e2cf6b4c388253a2bd5d511442/setup.py", line 15, in get_boost_version                                                                                                       out = subprocess.check_output(                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^                                                                           File "/usr/lib/python3.11/subprocess.py", line 466, in check_output                                          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         File "/usr/lib/python3.11/subprocess.py", line 571, in run                                                   raise CalledProcessError(retcode, process.args,
>       subprocess.CalledProcessError: Command 'ldconfig -p | grep -E 'libboost_python.*\.so '' returned non-zero exit status 1.                                                                                              [end of output]                                                                                                                                                                                                   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

 

Then try:
` sudo apt-get install libboost-all-dev
`

And then try again.

**Comment by tablatronix** [comment]
Thanks, trying to install on debian,  its 20 minutes of googling errors and fixing them.
Everytime with python I swear, and its still complaining. ugh

Maybe a path issue with my venv
